<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration: create_audit_trail_table
 *
 * Target: "production" database (default connection).
 *
 * Critical differences from a standard Eloquent table:
 *   1. Primary key is VARCHAR(100) UUID string — NOT auto-increment integer.
 *   2. No `updated_at` column — audit records are immutable once written.
 *   3. `created_at` is NOT NULL with DEFAULT current_timestamp() (not nullable).
 *   4. `diff` is LONGTEXT with json_valid() CHECK constraint (MariaDB).
 *   5. Compound index on (type, who) for filtered list queries.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('audit_trail', function (Blueprint $table): void {
            // Legacy: id varchar(100) NOT NULL PRIMARY KEY
            // UUID v4 string — generated by AuditService, not the DB.
            $table->string('id', 100)->primary();

            // Legacy: type varchar(100) NOT NULL
            // Describes what kind of mutation occurred (e.g. 'device_update').
            $table->string('type', 100);

            // Legacy: reason varchar(100) DEFAULT NULL
            // Human-readable note provided by the acting user.
            $table->string('reason', 100)->nullable();

            // Legacy: who varchar(100) NOT NULL
            // JWT username of the user who triggered the mutation.
            $table->string('who', 100);

            // Legacy: created_at datetime NOT NULL DEFAULT current_timestamp()
            // Immutable write timestamp. Not managed by Eloquent timestamps.
            $table->dateTime('created_at')->useCurrent();

            // Legacy: diff longtext CHECK (json_valid(diff))
            // JSON object of shape: { field: { before: old, after: new }, ... }
            $table->longText('diff');
        });

        // json_valid CHECK constraint on diff (MariaDB / MySQL 8.0.16+)
        Schema::table('audit_trail', function (Blueprint $table): void {
            $table->check('json_valid(`diff`)', 'chk_audit_diff_json');
        });

        // Indexes from legacy DDL
        Schema::table('audit_trail', function (Blueprint $table): void {
            // Used by ORDER BY created_at (default sort in list endpoint)
            $table->index('created_at', 'idx_audit_created_at');

            // Used by WHERE type = ? AND/OR who = ? filter queries
            $table->index(['type', 'who'], 'idx_audit_type_who');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('audit_trail');
    }
};
